In [1]:
#1.reading form a URL
url <- "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
irisData <- read.table(file=url, header=FALSE, sep=",")
colnames(irisData) <- c("sepal_length",
                        "sepal_width",
                        "petal_length",
                        "petal_width",
                        "target_class")

In [2]:
#1.1transform the target class to a factor.
irisData$target_class <- as.factor(irisData$target_class)

In [3]:
#1.2 find the frequencies of the target class (Hint: table()).
table(irisData$target_class )


    Iris-setosa Iris-versicolor  Iris-virginica 
             50              50              50 

In [5]:
#1.3 print “sepal_length” and “sepal_width” of 2nd observation.
irisData[2, c("sepal_length","sepal_width")]

sepal_length sepal_width
2 4.9          3

In [6]:
#1.4 print “sepal_width” and “petal_length” of the last 5 observations.
irisData[(nrow(irisData)-4):nrow(irisData),c("sepal_width", "petal_length")]

sepal_width petal_length
146 3.0         5.2         
147 2.5         5.0         
148 3.0         5.2         
149 3.4         5.4         
150 3.0         5.1

In [7]:
#1.5 print the target class of the observations that are between 50th and 60th. Please note that 50th and 60th should be included [50th,60th].
irisData[50:60,c("target_class")]         #irisData$target_class[50:60] 

[1] Iris-setosa     Iris-versicolor Iris-versicolor Iris-versicolor
 [5] Iris-versicolor Iris-versicolor Iris-versicolor Iris-versicolor
 [9] Iris-versicolor Iris-versicolor Iris-versicolor
Levels: Iris-setosa Iris-versicolor Iris-virginica

In [10]:
#1.6 print “sepal_width” of the observations which has petal_width is between 0.1 and 0.5 [0.1, 0.5].
irisData[(irisData$petal_width >= 0.1) & (irisData$petal_width <= 0.5), "sepal_width"]

[1] 3.5 3.0 3.2 3.1 3.6 3.9 3.4 3.4 2.9 3.1 3.7 3.4 3.0 3.0 4.0 4.4 3.9 3.5 3.8
[20] 3.8 3.4 3.7 3.6 3.3 3.4 3.0 3.4 3.5 3.4 3.2 3.1 3.4 4.1 4.2 3.1 3.2 3.5 3.1
[39] 3.0 3.4 3.5 2.3 3.2 3.8 3.0 3.8 3.2 3.7 3.3

In [12]:
# 1.7 print “petal_length” of the observations that are less than 1.3 or higher than 5.
irisData[(irisData$petal_length<1.3) | (irisData$petal_length>5), "petal_length"]

[1] 1.1 1.2 1.0 1.2 5.1 6.0 5.1 5.9 5.6 5.8 6.6 6.3 5.8 6.1 5.1 5.3 5.5 5.1 5.3
[20] 5.5 6.7 6.9 5.7 6.7 5.7 6.0 5.6 5.8 6.1 6.4 5.6 5.1 5.6 6.1 5.6 5.5 5.4 5.6
[39] 5.1 5.1 5.9 5.7 5.2 5.2 5.4 5.1

In [14]:
#2 Define a list by using the sepal_length of the first 10 observations and target_class of the last five observations of the Iris dataset. Set column names of the list.
my_list <- list(irisData$sepal_length[1:10], irisData$target_class[(nrow(irisData)-4):nrow(irisData)])
my_list
names(my_list) <- c("sepal_length", "target_class")
my_list

[[1]]
 [1] 5.1 4.9 4.7 4.6 5.0 5.4 4.6 5.0 4.4 4.9

[[2]]
[1] Iris-virginica Iris-virginica Iris-virginica Iris-virginica Iris-virginica
Levels: Iris-setosa Iris-versicolor Iris-virginica

$sepal_length
 [1] 5.1 4.9 4.7 4.6 5.0 5.4 4.6 5.0 4.4 4.9

$target_class
[1] Iris-virginica Iris-virginica Iris-virginica Iris-virginica Iris-virginica
Levels: Iris-setosa Iris-versicolor Iris-virginica

In [17]:
#3 Create two different matrices (5x5) by using the petal_width of the first 50 observations of the Iris dataset. Then;
my_vec <- irisData$petal_width[1:50]
X <- matrix(my_vec[1:25], nrow=5)
Y <- matrix(my_vec[26:50], nrow=5)
X

[,1] [,2] [,3] [,4] [,5]
[1,] 0.2  0.4  0.2  0.4  0.2 
[2,] 0.2  0.3  0.2  0.4  0.4 
[3,] 0.2  0.2  0.1  0.3  0.2 
[4,] 0.2  0.2  0.1  0.3  0.5 
[5,] 0.2  0.1  0.2  0.3  0.2

In [19]:
# 3.1 print the sum of the matrice
X+Y

[,1] [,2] [,3] [,4] [,5]
[1,] 0.4  0.6  0.4  0.7  0.5 
[2,] 0.6  0.7  0.4  0.7  0.6 
[3,] 0.4  0.3  0.2  0.5  0.4 
[4,] 0.4  0.4  0.3  0.9  0.7 
[5,] 0.4  0.2  0.4  0.7  0.4

In [20]:
# 3.2 perform matrix multiplication and print the result.
X %*% Y

[,1] [,2] [,3] [,4] [,5]
[1,] 0.36 0.32 0.26 0.54 0.30
[2,] 0.36 0.30 0.28 0.59 0.32
[3,] 0.24 0.21 0.19 0.40 0.22
[4,] 0.30 0.24 0.25 0.52 0.28
[5,] 0.22 0.18 0.18 0.39 0.22

In [22]:
# 3.2 take the transpose of the two matrices and assign them to two variables.
X_t <- t(X)
X_t
Y_t <- t(Y)
Y_t

[,1] [,2] [,3] [,4] [,5]
[1,] 0.2  0.2  0.2  0.2  0.2 
[2,] 0.4  0.3  0.2  0.2  0.1 
[3,] 0.2  0.2  0.1  0.1  0.2 
[4,] 0.4  0.4  0.3  0.3  0.3 
[5,] 0.2  0.4  0.2  0.5  0.2

[,1] [,2] [,3] [,4] [,5]
[1,] 0.2  0.4  0.2  0.2  0.2 
[2,] 0.2  0.4  0.1  0.2  0.1 
[3,] 0.2  0.2  0.1  0.2  0.2 
[4,] 0.3  0.3  0.2  0.6  0.4 
[5,] 0.3  0.2  0.2  0.2  0.2

In [23]:
# 3.3 bind the first matrix to the transpose of the first matrix by row.
X_t <- rbind(X_t, X)
X_t

[,1] [,2] [,3] [,4] [,5]
 [1,] 0.2  0.2  0.2  0.2  0.2 
 [2,] 0.4  0.3  0.2  0.2  0.1 
 [3,] 0.2  0.2  0.1  0.1  0.2 
 [4,] 0.4  0.4  0.3  0.3  0.3 
 [5,] 0.2  0.4  0.2  0.5  0.2 
 [6,] 0.2  0.4  0.2  0.4  0.2 
 [7,] 0.2  0.3  0.2  0.4  0.4 
 [8,] 0.2  0.2  0.1  0.3  0.2 
 [9,] 0.2  0.2  0.1  0.3  0.5 
[10,] 0.2  0.1  0.2  0.3  0.2

In [24]:
# 3.4 bind the second matrix to the transpose of the second matrix by column.
Y_t <- cbind(Y_t, Y)
Y_t

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,] 0.2  0.4  0.2  0.2  0.2  0.2  0.2  0.2  0.3  0.3  
[2,] 0.2  0.4  0.1  0.2  0.1  0.4  0.4  0.2  0.3  0.2  
[3,] 0.2  0.2  0.1  0.2  0.2  0.2  0.1  0.1  0.2  0.2  
[4,] 0.3  0.3  0.2  0.6  0.4  0.2  0.2  0.2  0.6  0.2  
[5,] 0.3  0.2  0.2  0.2  0.2  0.2  0.1  0.2  0.4  0.2

In [35]:
#4 Read the Mall Customers dataset (https://www.kaggle.com/shwetabh123/mall-customers). According to Mall Customers dataset, perform the followings:
setwd("C:/Users/Deniz/Data")  #getwd

In [36]:
fileName <- "Mall_Customers.csv"
my_customers <- read.table(file=fileName, header=TRUE, sep=",")
head(my_customers)

CustomerID Genre  Age Annual.Income..k.. Spending.Score..1.100.
1 1          Male   19  15                 39                    
2 2          Male   21  15                 81                    
3 3          Female 20  16                  6                    
4 4          Female 23  16                 77                    
5 5          Female 31  17                 40                    
6 6          Female 22  17                 76

In [37]:
#4.1 assign the CustomerID column as row names of the dataset, then delete the first column of the dataset.
rownames(my_customers) <- my_customers$CustomerID
my_customers <- my_customers[,-1]
head(my_customers)

Genre  Age Annual.Income..k.. Spending.Score..1.100.
1 Male   19  15                 39                    
2 Male   21  15                 81                    
3 Female 20  16                  6                    
4 Female 23  16                 77                    
5 Female 31  17                 40                    
6 Female 22  17                 76

In [38]:
#4.2 transform the genre to a factor.
my_customers$Genre <- as.factor(my_customers$Genre)
class(my_customers$Genre)

[1] "factor"

In [39]:
#4.3 save the dataset as RData file. Then write the R code that loads the dataset.
#save(my_customers, file = "my_cust.RData")
#load(file = "my_cust.RData")

In [45]:
#4.4 change names of the last two columns as “income” and “spendingScore”, respectively.
colnames(my_customers)[3:4] <- c("income", "spendingScore")
head(my_customers)

Genre  Age income spendingScore
1 Male   19  15     39           
2 Male   21  15     81           
3 Female 20  16      6           
4 Female 23  16     77           
5 Female 31  17     40           
6 Female 22  17     76

In [58]:
#4.5 create the subset of the dataset in which age is between 40 and 45 [40, 45], or income is greater than 100.
my_custSubset <- my_customers[(my_customers$Age >= 40 & my_customers$Age <= 45),]
my_custSubset

Genre  Age income spendingScore
27  Female 45   28    32           
29  Female 40   29    31           
37  Female 42   34    17           
67  Female 43   48    50           
77  Female 45   54    53           
78  Male   40   54    48           
94  Female 40   60    40           
123 Female 40   69    58           
127 Male   43   71    35           
128 Male   40   71    95           
137 Female 44   73     7           
151 Male   43   78    17           
153 Female 44   78    20           
167 Male   42   86    20           
171 Male   40   87    13           
185 Female 41   99    39           
189 Female 41  103    17           
197 Female 45  126    28

Genre  Age income spendingScore
1   Male   19  15     39           
2   Male   21  15     81           
3   Female 20  16      6           
4   Female 23  16     77           
5   Female 31  17     40           
6   Female 22  17     76           
7   Female 35  18      6           
8   Female 23  18     94           
9   Male   64  19      3           
10  Female 30  19     72           
11  Male   67  19     14           
12  Female 35  19     99           
13  Female 58  20     15           
14  Female 24  20     77           
15  Male   37  20     13           
16  Male   22  20     79           
17  Female 35  21     35           
18  Male   20  21     66           
19  Male   52  23     29           
20  Female 35  23     98           
21  Male   35  24     35           
22  Male   25  24     73           
23  Female 46  25      5           
24  Male   31  25     73           
25  Female 54  28     14           
26  Male   29  28     82           
27  Female 45  28     32           
28  Male   35  28     61           
29  Female 40  29     31           
30  Female 23  29     87           
... ...    ... ...    ...          
171 Male   40   87    13           
172 Male   28   87    75           
173 Male   36   87    10           
174 Male   36   87    92           
175 Female 52   88    13           
176 Female 30   88    86           
177 Male   58   88    15           
178 Male   27   88    69           
179 Male   59   93    14           
180 Male   35   93    90           
181 Female 37   97    32           
182 Female 32   97    86           
183 Male   46   98    15           
184 Female 29   98    88           
185 Female 41   99    39           
186 Male   30   99    97           
187 Female 54  101    24           
188 Male   28  101    68           
189 Female 41  103    17           
190 Female 36  103    85           
191 Female 34  103    23           
192 Female 32  103    69           
193 Male   33  113     8           
194 Female 38  113    91           
195 Female 47  120    16           
196 Female 35  120    79           
197 Female 45  126    28           
198 Male   32  126    74           
199 Male   32  137    18           
200 Male   30  137    83